#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 283160-web-01 52.201.147.119:80 check
        server 283160-web-02 52.91.121.196:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
