#!/usr/bin/env bash
# The contents of the file `/etc/passwd` are displayed.
# Only the username, user id, and user home directory path are displayed.

while IFS= read -r passwd;
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
