#!/usr/bin/env bash
# Apache log files in list format are parsed.
#   Displays Group visitors by IP and HTTP status code.
#   While displaying the number of occurrences, IP, and HTTP status

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
