#!/usr/bin/env bash
# ssh config file

# Host *
# SendEnv LANG LC_*
# HashKnownHosts yes
# GSSAPIAuthentication yes
# GSSAPIDelegateCredentials no
# IdentityFile ~/.ssh/school
# PasswordAuthentication no

OR
Host 52.201.147.119
IdentityFile ~/.ssh/school
PasswordAuthentication no
